python ./test.py --datapath "D:/FYP/Code/DCAMA/datasets" \
                 --benchmark serp \
                 --fold 0 \
                 --bsz 1 \
                 --nworker 0 \
                 --backbone resnet50 \
                 --logpath "./logs" \
                 --load "D:/FYP/Code/DCAMA/logs/best_model.pt" \
                 --nshot 1 \
                 --vispath "./vis_5" \
                 --visualize
